#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_die --message="DON'T USE THIS BRANCH FOR ANYTHING BUT INTERMEDIATE UPGRADE"